### PR TITLE
Added support for Xiaomi Philips Eyecare Smart Lamp 2

### PR DESCRIPTION
**Pull request by kuduka**
Added initial support for Xiaomi Philips Eyecare Smart Lamp 2

Usage: mieye [OPTIONS] COMMAND [ARGS]...

  A tool to command Xiaomi Philips Eyecare Smart Lamp 2.

Options:
  --ip TEXT
  --token TEXT
  -d, --debug
  --help        Show this message and exit.

Commands:
  ambient_off     Ambient Light off.
  ambient_on      Ambient Light on.
  bl_off          Night Light off.
  bl_on           Night Light on.
  delay_off       Set delay off in minutes.
  discover        Search for plugs in the network.
  notify_off      Eye Fatigue Reminder off.
  notify_on       Eye Fatigue Reminder On.
  off             Power off.
  on              Power on.
  set_amb_bright  Set Ambient Light brightness level.
  set_bright      Set brightness level.
  set_scene       Set eyecare scene number.
  status          Returns the state information.

### CODE REVIEW

**Comment by rytilahti** [comment]
Could you please run `mirobo -d info` on the current master and provide the printed out model?

**Comment by kuduka** [comment]
Device ID is the same one as in this PR, although no idea what is that 55249:

   0x02f9: "Xiaomi Philips Eyecare Smart Lamp 2

With this lamp mirobo crashes as it doesn't have get_status method:

```
(venv) [kuduk@xps13 python-mirobo]$ venv/bin/mirobo --ip 192.168.1.191 --token xxx -d 
INFO:mirobo.vacuum_cli:Debug mode active
ERROR:mirobo.vacuum_cli:Unable to read the stored msgid: [Errno 2] No such file or directory: '/tmp/python-mirobo.seq'
DEBUG:mirobo.vacuum_cli:Connecting to 192.168.1.191 with token d177973a1fa6262b0831792aad342fad
DEBUG:mirobo.protocol:Unable to decrypt, returning raw bytes.
DEBUG:mirobo.device:Discovered 761 55249 with ts: 1970-01-01 00:10:19
DEBUG:mirobo.device:192.168.1.191:54321 >>: {'id': 1, 'method': 'get_status'}
DEBUG:mirobo.device:192.168.1.191:54321 (ts: 1970-01-01 00:10:19, id: 1) << {'id': 1, 'error': {'code': -32600, 'message': 'Req object invalid.'}}
Traceback (most recent call last):
```

**Comment by rytilahti** [comment]
That's discovery, I mean you have to try `mirobo -d info`, it will show something similar to this:
`rockrobo.vacuum.v1 v3.3.9_003077 (28:6C:07:XX:XX:XX) @ 192.168.XXX.XXX - token: 476e6b70343055483XXXXXXXXXXXXX`. The first part is the model name, the second one the FW version etc. With `-d` you will see the whole response though, maybe there is also some other interesting parts so it's worth checking out.

**Comment by kuduka** [comment]
I just saw know my mistake, here's the good one!
```

(venv) [kuduk@xps13 python-mirobo]$ venv/bin/mirobo --ip 192.168.1.191 --token d177973a1fa6262b0831792aad342fad -d info
INFO:mirobo.vacuum_cli:Debug mode active
<_io.TextIOWrapper name='/tmp/python-mirobo.seq' mode='r' encoding='UTF-8'>
DEBUG:mirobo.vacuum_cli:Read stored sequence ids: {'seq': 1, 'manual_seq': 0}
DEBUG:mirobo.vacuum_cli:Connecting to 192.168.1.191 with token d177973a1fa6262b0831792aad342fad
DEBUG:mirobo.protocol:Unable to decrypt, returning raw bytes.
DEBUG:mirobo.device:Discovered 761 55249 with ts: 1970-01-01 00:00:07
DEBUG:mirobo.device:192.168.1.191:54321 >>: {'id': 2, 'method': 'miIO.info', 'params': []}
DEBUG:mirobo.device:192.168.1.191:54321 (ts: 1970-01-01 00:00:07, id: 2) << {'result': {'life': 7, 'token': 'd177973a1fa6262b0831792aad342fad', 'mac': '28:6C:07:2A:9B:BC', 'fw_ver': '1.2.8', 'hw_ver': 'ESP8266', 'model': 'philips.light.sread1', 'mcu_fw_ver': '0024', 'wifi_fw_ver': '1.4.0(30e0bd0)', 'ap': {'rssi': -69, 'ssid': 'XarxaCasa', 'bssid': '5C:35:3B:EA:97:DE'}, 'netif': {'localIp': '192.168.1.191', 'mask': '255.255.255.0', 'gw': '192.168.1.1'}, 'mmfree': 11720}, 'id': 2}
philips.light.sread1 v1.2.8 (28:6C:07:2A:9B:BC) @ 192.168.1.191 - token: d177973a1fa6262b0831792aad342fad
DEBUG:mirobo.vacuum_cli:Full response: {'ap': {'bssid': '5C:35:3B:EA:97:DE', 'rssi': -69, 'ssid': 'XarxaCasa'},
 'fw_ver': '1.2.8',
 'hw_ver': 'ESP8266',
 'life': 7,
 'mac': '28:6C:07:2A:9B:BC',
 'mcu_fw_ver': '0024',
 'mmfree': 11720,
 'model': 'philips.light.sread1',
 'netif': {'gw': '192.168.1.1',
           'localIp': '192.168.1.191',
           'mask': '255.255.255.0'},
 'token': 'd177973a1fa6262b0831792aad342fad',
 'wifi_fw_ver': '1.4.0(30e0bd0)'}
DEBUG:mirobo.vacuum_cli:Writing {'seq': 2, 'manual_seq': 0} to /tmp/python-mirobo.seq

```

**Comment by rytilahti** [comment]
Thanks, that's looking good! Interesting that it sports ESP8266 (hw_ver) :-) I think this can actually be merged now, it just needs some refactoring after refactoring the client tool to behave nicer.

**Comment by rytilahti** [comment]
As the necessary information for refactoring the client tool is either here or in the source code, let's merge this as I'm unsure when I get some time to look into refactoring the tool.

**Pull request merged**
